global:
  scrape_interval: 5s

scrape_configs:
  - job_name: consumer

    static_configs:
      - targets:
          - consumer:8001

  - job_name: simulation

    static_configs:
      - targets:
          - simulation:8002        