name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Build consumer image
        run: docker build ./consumer

      - name: Build app image
        run: docker build ./app

      - name: Build simulation image
        run: docker build ./simulation  

      - name: Run tests
        run: |
          echo "No tests yet"  # позже заменим на pytest

  build-and-push:

    needs: test

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build consumer image
        run: docker build ./consumer -t ${{ secrets.DOCKERHUB_USERNAME }}/telemetry-consumer:latest

      - name: Push consumer image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/telemetry-consumer:latest

      - name: Build simulation image
        run: docker build ./simulation -t ${{ secrets.DOCKERHUB_USERNAME }}/telemetry-simulation:latest

      - name: Push simulation image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/telemetry-simulation:latest  

      - name: Build app image
        run: docker build ./app -t ${{ secrets.DOCKERHUB_USERNAME }}/telemetry-api:latest

      - name: Push app image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/telemetry-api:latest  